spring:
  #数据源配置
  datasource:
    username: user01
    password: user01
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  #Hibernate原语
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #DDL级别
    hibernate:
      ddl-auto: update
